# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "hydris-pygeoapi"
  tags:
  - "internal"
spec:
  type: "service"
  lifecycle: "production"
  owner: "handsfree"
  system: "hydris"
